### ISSUE TITLE
Differences with upstream

### ISSUE THREAD

**Issue by Guekka** [DoctorRyner/helix#31]
Hello. I know you are probably maintaining this fork for your own usage. But some features you have integrated might be of use to me, and I'd like to know the differences between this fork and the upstream project.
Would you mind writing a bit about it in the readme?

**Comment by DoctorRyner** [comment]
Sure, I can list some thing a top of my head.

1. File explorer: space + e
2. Copilot: ctrl + n from this https://github.com/helix-editor/helix/pull/6865
3. alexandria theme I made

I don't quite remember if something else is fixed/added, I just needed some tweaks in the editor so I can use it as my daily driver until plugins support is released.

I also store my extensive config here.

Hm, helix team seems to be not developing the editor as extensively as before but maybe it's my imagination. Helix is great but still needs a lot of work. It's pretty good already for 90% of the job but I still have VS Code/JetBrains products for some cases like 'git blame'

**Comment by Guekka** [comment]
Thank you. So compared to [the Copilot PR author's fork](https://github.com/AlexanderDickie/helix/) (which I discovered after this post), you have the file explorer and your custom configuration

> Hm, helix team seems to be not developing the editor as extensively as before but maybe it's my imagination. Helix is great but still needs a lot of work. It's pretty good already for 90% of the job but I still have VS Code/JetBrains products for some cases like 'git blame'.

In particular, I feel like progress on the plugin system is very slow. I know they don't want to mess it up, but it's really slowing down helix adoption
